---
abstract: 'an evented configuration file in a unique and clean format'
author:
  - 'Mitchell Cooper <cooper@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 0
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.112150'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Evented-Configuration
provides:
  Evented::Configuration:
    file: lib/Evented/Configuration.pm
    version: 3.31
requires:
  Evented::Object: 3.50
  perl: 5.010
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://github.com/cooper/evented-configuration
version: 3.31
